name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - 'main'
  tags:
   include:
    - '*'
  paths:
    exclude:
      - docker/rstudio-image

schedules:
  - cron: "0 12 1 * *"
    displayName: Monthly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      endpoint: statisticsnorway

variables:
    # Mandatory
    # The fully qualified name of the Docker image e.g. eu.gcr.io/prod-bip/ssb/stratus/am-hello-world
  - name: imageName
    value: 'eu.gcr.io/prod-bip/ssb/s782/rstudio-hub-onprem'

  - name: imageNameNexus
    value: 'nexus.ssb.no:8437/prod-bip/ssb/s782/rstudio-hub-onprem'

    # Mandatory
    # The fully qualified name of the image repository e.g. prod-bip/ssb/stratus/am-hello-world
  - name: repoName
    value: 'prod-bip/ssb/s782/rstudio-hub-onprem'

    # This should be left as default for most cases. Override if you have a particular reason.
  - name: timeBetweenRetriesVulnerabilityScan
    value: '15000'

  - name: imageTagAfterVulnerabilityScan
    value: $(Build.SourceBranchName)-$(Build.SourceVersion)

    # It's unusual to have a Dockerfile named anything else. This may be overridden for those unusual cases.
  - name: Dockerfile
    value: 'docker/jupyterhub/Dockerfile'

jobs:
  - job: dockerBuildAndDockerPush
    timeoutInMinutes: 150
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: docker/docker-build-image-and-push-to-gcr.yml@templates
        parameters:
          imageName: $(imageName)
          repoName: $(repoName)
          Dockerfile: $(DockerFile)
          timeBetweenRetriesVulnerabilityScan: $(timeBetweenRetriesVulnerabilityScan)
          skipImageVulnerabilityScan: 'true'

      # Need to tag 'latest' image (used by docker-tag-for-production)
      - script: |
          cat $(gcrJsonKey.secureFilePath) | docker login -u _json_key --password-stdin ${{ variables.imageHost }}
          docker pull ${{ variables.imageName }}:imagescan-${{ variables.imageTagAfterVulnerabilityScan }}
          docker tag ${{ variables.imageName }}:imagescan-${{ variables.imageTagAfterVulnerabilityScan }} ${{ variables.imageName }}:latest
          docker push ${{ variables.imageName }}:latest
        displayName: "Retagging latest image"
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    # Job which pulls the Docker image with the 'latest' tag from GCR, tags this
    # with the git tag, and pushes that back to GCR.
    # The job triggers when any tag was committed to GitHub, which means all tags in
    # the code repo are propagated to the corresponding (newly built) image in GCR.
  - template: docker/docker-tag-for-production.yml@templates
    parameters:
      tagToTag: 'latest'
      gcrImageName: ${{ variables.imageName }}
  
  - job: deployToStaging
    dependsOn: dockerBuildAndDockerPush
    pool:
      name: jupyterhub-onprem-staging
      demands:
      - agent.name -equals staging-agent-1

    displayName: "Deploying to staging"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
      - script: |
          set -e
          
          IMAGE=${{ variables.imageNameNexus }}:latest
          echo "Pulling $IMAGE"
          docker pull $IMAGE
          echo "Removing dangling images"
          docker image prune --force
          REPO="$HOME/rstudio-onprem"
          if ! [ -d "$REPO" ]
          then
              echo "repo $REPO does not exist locally, cloning it."
              git clone https://github.com/statisticsnorway/rstudio-onprem.git $REPO
              echo "creating necessary directories for ssl and postgres assuming they don't already exist"
              mkdir -p $HOME/secrets/ssl
              mkdir -p $HOME/secrets/postgres
              cd $REPO
                
              echo "creating docker network for jupyterhub"
              make network
                
              echo "creating docker volumes for jupyterhub"
              make volumes
              echo "creating postgresql secret for jupyterhub"
              make postgres-pw-gen
          fi
          cd $REPO
          git pull
            
          SERVICE_FILE=/etc/systemd/system/jupyterhub.service
          if cmp -s -- "$SERVICE_FILE" "$REPO/docker/jupyterhub/jupyterhub.service"; then
              echo "Service files are the same, restarting service."
              sudo systemctl restart jupyterhub.service
          else
              echo "Service file $SERVICE_FILE does not exist or is not equal to the recently pulled one."
              sudo cp "$REPO/docker/jupyterhub/jupyterhub.service" "/etc/systemd/system/"
              echo "enabling service."
              sudo systemctl enable jupyterhub.service
              echo "starting service."
              sudo systemctl start jupyterhub.service
          fi
  - job: deployToProd
    dependsOn: dockerBuildAndDockerPush
    pool:
      name: jupyterhub-onprem-prod
      demands:
      - agent.name -equals prod-agent

    displayName: "Deploying to prod"
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    steps:
      - script: |
          set -e
          REPO="$HOME/jupyterhub-onprem"
          if ! [ -d "$REPO" ]
          then
              echo "repo $REPO does not exist locally, cloning it."
              git clone https://github.com/statisticsnorway/jupyterhub-onprem.git $REPO
              echo "creating necessary directories for ssl and postgres assuming they don't already exist"
              mkdir -p $HOME/secrets/ssl
              mkdir -p $HOME/secrets/postgres
              cd $REPO
                  
              echo "creating docker network for jupyterhub"
              make network
              
              echo "creating docker volumes for jupyterhub"
              make volumes
              echo "creating postgresql secret for jupyterhub"
              make postgres-pw-gen
          fi
          
          cd $REPO
          git pull
          echo "Getting the latest git tag"
          git fetch --tags
          TAG=`git describe --tags`
          echo "Found tag $TAG"
          sed "s/<TAG>/$TAG/g" docker/jupyterhub/.env.prod > docker/jupyterhub/.env
          
          IMAGE=${{ variables.imageNameNexus }}:$TAG
          echo "Pulling $IMAGE"
          docker pull $IMAGE
          echo "Removing dangling images"
          docker image prune --force
          SERVICE_FILE=/etc/systemd/system/jupyterhub.service
          if cmp -s -- "$SERVICE_FILE" "$REPO/docker/jupyterhub/jupyterhub.service"; then
              echo "Service files are the same, restarting service."
              sudo systemctl restart jupyterhub.service
          else
              echo "Service file $SERVICE_FILE does not exist or is not equal to the recently pulled one."
              sudo cp "$REPO/docker/jupyterhub/jupyterhub.service" "/etc/systemd/system/"
              echo "enabling service."
              sudo systemctl enable jupyterhub.service
              echo "starting service."
              sudo systemctl start jupyterhub.service
          fi
      